version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: alumnity-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alumnity
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@alumnity.com
      PGADMIN_DEFAULT_PASSWORD: admin123

volumes:
  pgdata:
